index:
    path: /
    controller: App\Controller\DefaultController::index

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

account:
    resource: '../src/Account/Controller/'
    type: annotation
    prefix: /api/{_locale}
    requirements:
      _locale: pl|en
    defaults: { _locale: pl}

authentication:
    resource: '../src/Authentication/Controller/'
    type: annotation
    prefix: /api/{_locale}
    requirements:
      _locale: pl|en
    defaults: { _locale: pl}